version: '3.8'

services:
  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis_documents_vector_store
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis-documents-data:/data
    restart: always

volumes:
  redis-documents-data:
    driver: local