services:
  redis:
    image: redis:alpine
    container_name: redis
    deploy:
      resources:
        limits:
          cpus: '0.24'
          memory: 64M
        reservations:
          cpus: '0.12'
          memory: 48M
    ports:
      - "6379:6379"
    command: redis-server --requirepass "root" --maxmemory 50mb --maxmemory-policy allkeys-lru
  postgres:
    image: pgvector/pgvector:pg16
    container_name: postgres
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 128M
        reservations:
          cpus: '0.25'
          memory: 64M
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./batch.sql:/docker-entrypoint-initdb.d/batch.sql
    command: postgres -c shared_buffers=64MB -c work_mem=4MB -c max_connections=50
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    deploy:
      resources:
        limits:
          cpus: '0.36'
          memory: 128M
        reservations:
          cpus: '0.12'
          memory: 48M
    ports:
      - "8759:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=10m'
      - '--storage.tsdb.wal-compression'
      - '--storage.tsdb.min-block-duration=10m'
      - '--storage.tsdb.max-block-duration=10m'
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    deploy:
      resources:
        limits:
          cpus: '0.86'
          memory: 256M
        reservations:
          cpus: '0.24'
          memory: 48M
    ports:
      - "8760:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_ANALYTICS_REPORTING_ENABLED=false
      - GF_ANALYTICS_CHECK_FOR_UPDATES=false
      - GF_ALERTING_ENABLED=false
      - GF_UNIFIED_ALERTING_ENABLED=false
      - GF_EXPLORE_ENABLED=false
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.12'
          memory: 128M
    ports:
      - "9411:9411"
    environment:
      - STORAGE_TYPE=mem
      - JAVA_OPTS=-Xms64m -Xmx192m
volumes:
  postgres-data:
    driver: local